import turtle
turtle.color("green")
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(25)
turtle.left(90)
turtle.end_fill()
turtle.forward(150)

turtle.up()
turtle.backward(170)
turtle.down()
turtle.begin_fill()
turtle.color("brown")
turtle.backward(150)
turtle.left(90)
turtle.backward(100)
turtle.left(90)
turtle.backward(150)
turtle.left(90)
turtle.backward(100)
turtle.left(90)
turtle.end_fill()

turtle.exitonclick()