import turtle

turtle.color("red")
turtle.forward(100)
turtle.up()
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.down()
turtle.forward(100)
turtle.up()
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.down()
turtle.forward(100)
turtle.up()
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.down()
turtle.forward(100)
turtle.up()
turtle.forward(50)
turtle.left()
turtle.forward(50)
turtle.down()
turtle.exitonclick()


